stewards:
  - name: Divyansh013
    github: Divyansh013
    languages:
      - hi
  - name: takshittt
    github: takshittt
    languages:
      - hi
  - name: hana-cho
    github: hana-cho
    languages:
      - ko
  - name: limzykenneth
    github: limzykenneth
    languages:
      - zh-Hans
  - name: lirenjie95
    github: lirenjie95
    languages:
      - zh-Hans

