name: 🌱 New Feature Request
description: Request a new feature be added.
labels: [ Feature Request ]
body:
  - type: textarea
    attributes:
      label: Increasing Access
      description: How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js? (If you're not sure, you can type "Unsure" here and let others from the community offer their thoughts.)
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Most appropriate sub-area of p5.js?
      options:
        - Home
        - Reference
        - Tutorials
        - Examples
        - Contribute
        - Community (Sketches, Libraries, Events)
        - About
        - Other (specify if possible)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature request details
    validations:
      required: true