import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";
import { generateEntryId } from "../shared";

/**
 * Community education resources sourced from the Processing Foundation's
 * Are.na channel. Generated by `npm run build:arena-resources` — see
 * src/scripts/builders/arena-resources.ts.
 */
export const arenaResourcesCollection = defineCollection({
  loader: glob({
    pattern: "**/*.yaml",
    base: "./src/content/arena-resources",
    generateId: generateEntryId,
  }),
  schema: () =>
    z.object({
      areNaId: z.number(),
      title: z.string(),
      description: z.string().optional(),
      sourceUrl: z.url().optional(),
      sourceTitle: z.string().optional(),
      imageUrl: z.url().optional(),
      /* Parsed from the block's "By: ..." line - required, since blocks
       * without one are skipped by the build script (see
       * parseStructuredDescription in arena-resources.ts) */
      author: z.string(),
      /* Hashtags parsed from the block description, e.g. "p5jsv2", "english" */
      tags: z.array(z.string()),
    }),
});
