name: Test, typecheck, and lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npm run check

  check-ts-ignore-check:
    name: Check ts-ignore
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: get_changed_files
        uses: tj-actions/changed-files@v45

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Run TS Ignore Check
        run: python3 .github/scripts/detect_ts_ignore.py --files ${{ steps.get_changed_files.outputs.all_changed_files }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        env:
          SKIP_BUILD_COMPRESS: 1
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run build
